#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2026.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Mon Aug 31 21:30:15 EEST 2026
# SW Build 6511674 on Tue Jun 16 11:01:26 MDT 2026
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2026.1
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj tb_led_counter_4bit_vlog.prj"
xvlog --incr --relax -prj tb_led_counter_4bit_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
